# -*- coding: utf-8 -*-
"""youtube-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGeZY_Ex0XgnOFrGCqZel3xvBSyF5sYz
"""

# Commented out IPython magic to ensure Python compatibility.


import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

import re
import ast
from youtube_transcript_api import YouTubeTranscriptApi
from langchain_community.tools import YouTubeSearchTool
from langchain_community.document_loaders import YoutubeLoader


import re
from urllib.parse import urlparse, parse_qs

def extract_video_ids(urls: list[str]) -> list[str]:
    video_ids = []
    for url in urls:
        parsed = urlparse(url)

        if parsed.hostname in ("www.youtube.com", "youtube.com"):
            qs = parse_qs(parsed.query)
            if "v" in qs:
                video_ids.append(qs["v"][0])
                continue
            match = re.match(r"^/embed/([a-zA-Z0-9_-]{11})", parsed.path)
            if match:
                video_ids.append(match.group(1))
                continue

        if parsed.hostname in ("youtu.be",):
            match = re.match(r"^/([a-zA-Z0-9_-]{11})", parsed.path)
            if match:
                video_ids.append(match.group(1))
                continue

        match = re.search(r"(?:v=|/)([a-zA-Z0-9_-]{11})", url)
        if match:
            video_ids.append(match.group(1))

    return video_ids

def extract_video_ids(urls) -> list[str]:
    pattern = r'v=([^"]+?)&pp='
    return [re.search(pattern, url).group(1) for url in urls if re.search(pattern, url)]


def get_youtube_urls(video_query: str, number_of_videos: int=1):
    return ast.literal_eval(YouTubeSearchTool().run(f"{video_query},{number_of_videos}"))

video_ids = extract_video_ids(get_youtube_urls("qualidade pior no gpt5", 5))

get_youtube_urls("qualidade pior no gpt5", 5)

extract_video_ids(get_youtube_urls("qualidade pior no gpt5", 5))

for video_id in video_ids:
    print(video_id)

# prompt = """
# ###### Instruções ######
# Você deve atuar como um sumarizador de conteúdo de vídeos. Para realizar essa
# tarefa, o conteúdo é transcrição do áudio do vídeo do YouTube.
# Para isso, siga as seguintes instruções:
# - Resuma o conteúdo extraindo o conteúdo mais importante
# - Use uma linguagem clara e objetiva
# - Explique o conteúdo de forma didática, como se estivesse ensinando uma pessoa
# leiga sobre o assunto
# - Gere um texto corrido explicando o conteúdo o vídeo
# - Não cite nomes de participantes do vídeo
# - Fale somente sobre o conteúdo abordado no vídeo
# - Não use expressões como: o vídeo fala sobre, o vídeo aborda,...

# ###### Transcrição ######
# {transcription}
# """

# llm = ChatOpenAI(model="gpt-4.1-nano", temperature=0.5)

# template = ChatPromptTemplate.from_messages(
#     ("system", prompt)
# )

# chain = template | llm

from youtube_transcript_api import YouTubeTranscriptApi

print(YouTubeTranscriptApi().fetch(
    video_id="hohBB5VM37E", 
    languages=["pt"]
    ))


# from youtube_comment_downloader import YoutubeCommentDownloader

# downloader = YoutubeCommentDownloader()
# comments = downloader.get_comments_from_url("https://www.youtube.com/watch?v=Mu3f4XIUluI")

# for comment in comments:
#     print(comment)

